sudo: false
language: python
python:
  - 3.6.2
before_script:
  - easy_install distribute
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - nosetests --with-coverage
  - coverage report
after_success:
  - coveralls

branches:
  only:
  - master

notifications:
  email: false  